/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageLogo: typeof import('./src/components/landing-page/ImageLogo.vue')['default']
    LandingPage: typeof import('./src/components/landing-page/LandingPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsersCardButton: typeof import('./src/components/landing-page/UsersCardButton.vue')['default']
    UsersSidebar: typeof import('./src/components/landing-page/UsersSidebar.vue')['default']
  }
}
